// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.browser.urlbar.matchBuckets", "suggestion:4,general:5");
user_pref("app.normandy.user_id", "eaea62cc-330a-444f-8c14-9ad373ccec48");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1528307894);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1528307654);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1528308014);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1528307774);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1528307623);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"18196\":1528307629566,\"18198\":1528307629566,\"18201\":1528307629566}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{a7548269-f759-40fe-9c76-39e1a966366a}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1528236000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1528307629);
user_pref("browser.onboarding.notification.prompt-count", 3);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1528307673407");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1528309478407");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1528307628272");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1528311228272");
user_pref("browser.search.countryCode", "DE");
user_pref("browser.search.region", "DE");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 977);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180516032328");
user_pref("browser.startup.homepage_override.mstone", "60.0.1");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"_8aa36f4f-6dc7-4c06-77af-5035170634fe_-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"_8aa36f4f-6dc7-4c06-77af-5035170634fe_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1528307626580");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "60.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installedDistroAddon.{8AA36F4F-6DC7-4c06-77AF-5035170634FE}", true);
user_pref("extensions.lastAppVersion", "60.0.1");
user_pref("extensions.lastPlatformVersion", "60.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"{8AA36F4F-6DC7-4c06-77AF-5035170634FE}\":\"84222d55-7e3d-4d36-98a1-1dc7d8d9bdbc\",\"screenshots@mozilla.org\":\"52287e61-9ba4-49c6-9007-5106f12bffab\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.benchmark.vp9.fps", 308);
user_pref("media.benchmark.vp9.versioncheck", 3);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x13c0");
user_pref("sanity-test.driver-version", "23.21.13.8813");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20180516032328");
user_pref("security.sandbox.content.tempDirSuffix", "{c02627e1-d463-4d37-ae52-5e03728eb1a3}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1528307623);
user_pref("toolkit.telemetry.cachedClientID", "e43441ab-388b-423a-986b-07cb376afd7b");
user_pref("toolkit.telemetry.previousBuildID", "20180516032328");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
